[tool.poetry]
name = "pycast-recorder"
version = "0.1.0"
description = ""
authors = ["Jono Hill <jonathan@hillnz.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aioschedule = "^0.5.2"
"ruamel.yaml" = "^0.16.0"
lxml = "^4.3"
aiohttp = "^3.5"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
rope = "^0.18.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
